version: '3'
services:
  #backend:
  # build:
  #    context: ./backend
  #    dockerfile: Dockerfile
  #  ports:
  #    - '5000:5000'
  #  environment:
  #    FLASK_ENV: 'dev'
  #    FLASK_APP: 'app.py'
  #  volumes:
  #    - ./app:/app
  #  depends_on:
  #    - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '4200:80'
    volumes:
      - ./frontend:/app
    #depends_on:
    #  - backend

  #redis:
  #  image: redis
  #  ports:
  #    - '6379:6379' 