version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - '5000:5000'
    environment:
      FLASK_ENV: 'development'
      FLASK_APP: 'app/main.py'
    volumes:
      - ./app:/app
    depends_on:
      - database

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - '4200:4200'
    command: npm start
    volumes:
      - ./frontend:/app
    depends_on: